; This data for the client to access
[Access]
session = sessions/rcdtool
id = 25684853
hash = 9c7ca43baa94e3dde2589431fed83fc3

[output]
directory = downloads

; Client settings
[Client]
timeout = 60000
device_model = scriptgram
lang_code = es-ES
fast_download = true
download_parts = 4
